# Generated by Django 3.1.4 on 2021-04-29 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=30)),
                ('contact2', models.CharField(blank=True, default='', max_length=30)),
                ('availablity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 52, 42, 5970))),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 52, 42, 6020))),
            ],
        ),
        migrations.CreateModel(
            name='OxygenSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=30)),
                ('contact2', models.CharField(blank=True, default='', max_length=30)),
                ('type_is', models.CharField(choices=[('Seller', 'Seller'), ('Filling', 'Filling Only'), ('Both', 'Both Available')], max_length=10)),
                ('availablity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 52, 42, 7020))),
            ],
        ),
    ]
