# Generated by Django 3.1.4 on 2021-04-29 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 54, 20, 956123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 54, 20, 956153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='oxygensupply',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 11, 54, 20, 956797, tzinfo=utc)),
        ),
    ]
