# Generated by Django 3.1.4 on 2021-04-29 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210429_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='contact2',
            new_name='other_contact',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 48, 25, 253875)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 48, 25, 253929)),
        ),
        migrations.AlterField(
            model_name='oxygensupply',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 48, 25, 255092)),
        ),
    ]
