# Generated by Django 3.1.4 on 2021-04-29 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210429_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='OxygenSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=30)),
                ('contact2', models.CharField(blank=True, default='', max_length=30)),
                ('type_is', models.CharField(choices=[('Seller', 'Seller'), ('Filling', 'Filling Only'), ('Both', 'Both Available')], max_length=10)),
                ('availablity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 57, 56, 174159))),
            ],
        ),
        migrations.DeleteModel(
            name='OxygenSupply',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 57, 56, 173599)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 57, 56, 173628)),
        ),
    ]
