# Generated by Django 3.1.4 on 2021-04-30 12:00

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210430_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 17, 30, 45, 185237)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 17, 30, 45, 185277)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ICU', 'ICU'), ('BEDS', 'BEDS'), ('VENTILATOR', 'VENTILATOR')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='oxygensupplier',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 17, 30, 45, 186031)),
        ),
        migrations.AlterField(
            model_name='oxygensupplier',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 17, 30, 45, 186056)),
        ),
    ]
