# Generated by Django 3.1.4 on 2021-05-01 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210501_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 143237))),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 143262))),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 140925)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 140960)),
        ),
        migrations.AlterField(
            model_name='med',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 142638)),
        ),
        migrations.AlterField(
            model_name='med',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 142665)),
        ),
        migrations.AlterField(
            model_name='oxygensupplier',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 141787)),
        ),
        migrations.AlterField(
            model_name='oxygensupplier',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 12, 54, 30, 141814)),
        ),
    ]
