# Generated by Django 3.1.4 on 2021-05-01 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210501_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 653250)),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 653285)),
        ),
        migrations.AlterField(
            model_name='med',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 654811)),
        ),
        migrations.AlterField(
            model_name='med',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 654836)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 655368)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 655391)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='oxygensupplier',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 654035)),
        ),
        migrations.AlterField(
            model_name='oxygensupplier',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 24, 57, 654061)),
        ),
    ]
